// fnt_main — the game's own font, drawn the game's own way.
//
// `scr_84_get_font("main")` resolves to `fnt_main` (display name
// "8bitoperator JVE", EmSize 12, ASCII 32..126). The extractor writes the
// font's texture-page region as a PNG plus the glyph table as JSON; both
// live in assets/gonermaker/ and are regenerated by
// tools/extract-gonermaker.sh from the player's own copy of the game.
//
// TWO TRAPS, both already paid for in knight-sim's render/font.js:
//
// 1. `shift` (the advance) and `w` (the inked width) are different numbers,
//    and a space has w = 0 with shift = 3 — so a w-based layout silently
//    deletes every space. None of that matters here, because…
// 2. …obj_writer does NOT advance by the glyph's shift. Its Draw ends every
//    character with a flat `wx += hspace` — 12 for typer 666 — so the Gaster
//    text is MONOSPACED at 12px regardless of the letter. Drawing it
//    proportionally is the single most visible way to get this wrong.

/** @returns {Promise<{img:HTMLImageElement, glyphs:Map<number,object>, meta:object}>} */
export async function loadFont(base = './assets/gonermaker/', name = 'fnt_main') {
  try {
    const [meta, img] = await Promise.all([
      fetch(`${base}${name}.json`).then((r) => {
        if (!r.ok) throw new Error(`${name}.json missing`);
        return r.json();
      }),
      new Promise((res, rej) => {
        const i = new Image();
        i.onload = () => res(i);
        i.onerror = () => rej(new Error(`${name}.png missing`));
        i.src = `${base}${name}.png`;
      }),
    ]);
    const glyphs = new Map();
    for (const g of meta.glyphs) glyphs.set(g.c, g);
    return { img, glyphs, meta, tints: new Map() };
  } catch (error) {
    console.warn(`Using browser font fallback: ${error.message}`);
    return { fallback: true, glyphs: new Map(), meta: {}, tints: new Map() };
  }
}

/**
 * A colour-multiplied copy of the page, cached.
 *
 * GML's `draw_set_color` MULTIPLIES the glyph, and the glyphs are
 * white-on-transparent — so a `source-in` fill reproduces it exactly, while
 * also being the only way to keep the edge alpha intact.
 */
function tinted(font, color) {
  let page = font.tints.get(color);
  if (page) return page;
  page = document.createElement('canvas');
  page.width = font.img.width;
  page.height = font.img.height;
  const g = page.getContext('2d');
  g.drawImage(font.img, 0, 0);
  g.globalCompositeOperation = 'source-in';
  g.fillStyle = color;
  g.fillRect(0, 0, page.width, page.height);
  font.tints.set(color, page);
  return page;
}

/** One character, at the pen position. `offset` is the glyph's left bearing. */
function blit(ctx, font, code, x, y, alpha, color) {
  const g = font.glyphs.get(code);
  if (!g || g.w <= 0 || g.h <= 0) return;
  ctx.globalAlpha = alpha;
  ctx.drawImage(color ? tinted(font, color) : font.img,
    g.x, g.y, g.w, g.h, Math.round(x + g.offset), Math.round(y), g.w, g.h);
}

/**
 * `draw_text` for one character with obj_writer's SPECIAL 2 — the glow the
 * Gaster typers (666 and 667) are set up with. Straight from the Draw event:
 *
 *     draw_set_alpha(1 * specfade);                       draw_text(wx, wy)
 *     draw_set_alpha((0.3 + sin(siner/14) * 0.1) * specfade);   4 cardinals
 *     draw_set_alpha((0.08 + sin(siner/14) * 0.04) * specfade); 4 diagonals
 *
 * The solid glyph goes down FIRST and the halo accumulates around it; the
 * pulse is one shared `siner`, incremented once per 30 Hz frame, so every
 * character on screen breathes together.
 */
export function drawCharSpecial2(ctx, font, ch, x, y, specfade, siner, color = null) {
  const code = ch.codePointAt(0);
  const near = (0.3 + Math.sin(siner / 14) * 0.1) * specfade;
  const far = (0.08 + Math.sin(siner / 14) * 0.04) * specfade;
  blit(ctx, font, code, x, y, 1 * specfade, color);
  blit(ctx, font, code, x + 1, y, near, color);
  blit(ctx, font, code, x - 1, y, near, color);
  blit(ctx, font, code, x, y + 1, near, color);
  blit(ctx, font, code, x, y - 1, near, color);
  blit(ctx, font, code, x + 1, y + 1, far, color);
  blit(ctx, font, code, x - 1, y - 1, far, color);
  blit(ctx, font, code, x - 1, y + 1, far, color);
  blit(ctx, font, code, x + 1, y - 1, far, color);
  ctx.globalAlpha = 1;
}

/** Plain `draw_text` — proportional, glyph shifts, no glow. The menus use it. */
export function drawText(ctx, font, text, x, y, { color = null, alpha = 1 } = {}) {
  if (font.fallback) {
    ctx.save();
    ctx.globalAlpha = alpha;
    ctx.fillStyle = color ?? '#ffffff';
    ctx.font = '12px monospace';
    ctx.textBaseline = 'top';
    ctx.fillText(String(text), x, y);
    ctx.restore();
    return ctx.measureText(String(text)).width;
  }
  let pen = x;
  for (const ch of String(text)) {
    const code = ch.codePointAt(0);
    const g = font.glyphs.get(code);
    if (!g) continue;
    blit(ctx, font, code, pen, y, alpha, color);
    pen += g.shift;
  }
  ctx.globalAlpha = 1;
  return pen - x;
}

/** `string_width` — the sum of the advances. DEVICE_CHOICE centres with it. */
export function textWidth(font, text) {
  if (font.fallback) {
    return String(text).length * 7.2;
  }
  let w = 0;
  for (const ch of String(text)) {
    const g = font.glyphs.get(ch.codePointAt(0));
    if (g) w += g.shift;
  }
  return w;
}
